name: "Ingest Work Environment Data"
description: "Automatically ingest the latest data from Arbetsmiljöverket."
inputs:
  github_token:
    description: "The GitHub token to use for deployment."
    required: true
  year:
    description: "The year the data is for."
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      with:
        run_install: true
        version: 10

    - run: pnpm install
      shell: bash
      working-directory: ${{ github.action_path }}
